apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  # Strimzi Operator (deployed first)
  - strimzi-operator.yaml
  # Kafka Cluster (depends on operator CRDs)
  - kafka-cluster.yaml
  # Kafka Connect Cluster (depends on Kafka cluster)
  - kafka-connect.yaml
  # Kafka Topics (can be created after cluster is ready)
  - kafka-topics.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: streaming
      app.kubernetes.io/part-of: cdc-platform
      app.kubernetes.io/managed-by: argocd

commonAnnotations:
  documentation: "https://strimzi.io/docs/"
  platform: "cdc-platform"
