---
# Kafka Cluster Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cdc-platform
  
  source:
    repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
    targetRevision: main
    path: k8s/kafka
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Custom health checks for Kafka resources
  ignoreDifferences:
    - group: kafka.strimzi.io
      kind: Kafka
      jsonPointers:
        - /spec/kafka/version
---
# Schema Registry Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cdc-platform
  
  source:
    repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
    targetRevision: main
    path: k8s/schema-registry
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m