apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
    targetRevision: main
    path: argocd/app-manifests/consumers

  destination:
    server: https://kubernetes.default.svc
    namespace: consumers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
