apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-jobs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
    targetRevision: main
    path: argocd/app-manifests/flink

  destination:
    server: https://kubernetes.default.svc
    namespace: flink

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Image update automation
  annotations:
    argocd-image-updater.argoproj.io/image-list: flink=296592524620.dkr.ecr.us-east-1.amazonaws.com/flink-jobs
    argocd-image-updater.argoproj.io/flink.update-strategy: latest
