apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: ingress-controller
    app.kubernetes.io/part-of: cdc-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.7.1
      helm:
        releaseName: aws-load-balancer-controller
        values: |
          clusterName: cdc-platform
          serviceAccount:
            create: false
            name: aws-load-balancer-controller
          region: us-east-1
          vpcId: vpc-03529f356914de651
          enableCertManager: false
          enableShield: false
          enableWaf: false
          enableWafv2: false
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          podLabels:
            app.kubernetes.io/name: aws-load-balancer-controller
            app.kubernetes.io/component: controller
    - repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
      targetRevision: main
      path: k8s/aws-load-balancer-controller
      directory:
        include: '{serviceaccount.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false  # kube-system already exists
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    # Ignore differences in webhook configurations managed by the controller
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
