---
# Flink Operator Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after Kafka
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cdc-platform

  source:
    repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
    targetRevision: main
    path: k8s/flink/operator

  destination:
    server: https://kubernetes.default.svc
    namespace: flink

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
# Flink Jobs Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-jobs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy after Debezium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cdc-platform

  source:
    repoURL: https://github.com/jbrcoleman/RealTimeCDC-Platform
    targetRevision: main
    path: k8s/flink/jobs

  destination:
    server: https://kubernetes.default.svc
    namespace: flink

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas