apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-servicemonitors
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/RealTimeCDC-Platform.git
    targetRevision: main
    path: k8s/monitoring/servicemonitors
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-alerts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/RealTimeCDC-Platform.git
    targetRevision: main
    path: k8s/monitoring/alerts
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
