apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: 296592524620.dkr.ecr.us-east-1.amazonaws.com/flink-sales-aggregations:latest
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-jobmanager
            taskmanager.numberOfTaskSlots: 2
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "cdc-platform-kafka-bootstrap.kafka.svc.cluster.local:9092"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
